config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :categories
  root 'articles#index'

  resources :articles
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :category
  belongs_to :user

  validates :title, :presence => true, :length => {:minimum=>3, :maximum=>50}
  validates :body, :presence => true, :length => {:minimum=>10, :maximum=>4999}

  paginates_per 7

  scope :desc_order, -> { order(created_at: :desc) }
  scope :without_highlights, -> (ids) { where("id NOT IN(#{ids})") if ids.present? }
  scope :filter_category, -> (category) { where category_id: category.id if category.present?}
  scope :filter_archive, lambda { |month_year|
    if month_year
      date = Date.strptime(month_year, "%B %Y")
      where(created_at: date.beginning_of_month..date.end_of_month.end_of_day)
    end
    }
  # Ex:- scope :active, -> {where(:active => true)}
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :articles, dependent: :restrict_with_error

  validates :name,
            :presence => true, 
            :length => {:minimum=>3, :maximum=>50},
            :uniqueness => {:case_sensitive => false}

  scope :sorted, -> { order(:name) }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles, dependent: :destroy

  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, and :omniauthable
  devise :database_authenticatable, 
         :registerable,
         :recoverable, 
         :rememberable, 
         :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  include Paginable

  before_action :authenticate_user!, except: %i[index show]
  before_action :set_article, only: %i[show edit update destroy]

  def index
    @categories = Category.sorted
    category = @categories.select { |c| c.name == params[:category] }[0] if params[:category].present?

    @highlights = Article.includes(:category, :user)
                         .filter_category(category)
                         .filter_archive(params[:month_year])
                         .desc_order
                         .first(3)

    highlight_ids = @highlights.pluck(:id).join(',')

    @articles = Article.includes(:category, :user)
                       .without_highlights(highlight_ids)
                       .filter_category(category)
                       .filter_archive(params[:month_year])
                       .desc_order
                       .page(current_page)

    @archives = Article.group_by_month(:created_at, format: "%B %Y").count
  end

  def show; end
  
  def new
    @article = current_user.articles.new    
  end

  def create
    @article = current_user.articles.new(article_params)

    if @article.save
      redirect_to @article, notice: "Article was successfully Created."
    else
      render :new
    end
  end

  def edit; end

  def update
    if @article.update(article_params)
      redirect_to @article, notice: "Article was successfully Updated."
    else
      render :edit
    end
  end

  def destroy
    @article.destroy

    redirect_to root_path, notice: "Article was successfully Destroyed."
  end  

  private

  def article_params
    params.require(:article).permit(:title, :body, :category_id)
  end

  def set_article
    @article = Article.find(params[:id])
    authorize @article
  end  
  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = policy_scope(Category.sorted)
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
    authorize @category
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)
    authorize @category

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_url, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to categories_url, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    if @category.destroy
      respond_to do |format|
        format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
        format.json { head :no_content }
      end
    else
      redirect_to categories_url, alert: @category.errors.messages[:base][0]
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/concerns/paginable.rb
module Paginable
  protected

  def current_page
    (params[:page] || 1).to_i
  end   
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_if(condition, template, record)
    render template, record if condition
  end
  
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def datebr(datetime)
    datetime.strftime('%B %e, %Y')
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/articles/_about.html.erb
<div class="p-4 mb-3 bg-light rounded">
  <h4 class="fst-italic">About</h4>
  <p class="mb-0">I'm João, 30 years old, and I'm learning Ruby on Rails using Bootstrap and this blog is a test of that.</p>
</div>

app/views/articles/_archives.html.erb
<div class="p-4">
  <h4 class="fst-italic">Archives</h4>
    <ol class="list-unstyled mb-0">      
      <% @archives.each do |month_year, count| %>
        <li>
          <%= link_to "#{month_year} (#{count})", articles_path(month_year: month_year), class: "link-primary #{'category-active' if month_year == params[:month_year]}" %>
        </li>
      <% end %>      
    </ol>
</div>

app/views/articles/_article.html.erb
<article class="blog-post">
  <h2 class="blog-post-title"><%= article.title %></h2>
  <p class="blog-post-meta"><%= render 'article_detail', article: article %></p>

  <p><%= truncate(article.body, length: 240) %></p>

  <p><%= link_to "Continue reading ...", article, class: "btn btn-link" %></p>
  
</article>

app/views/articles/_article_detail.html.erb
 <p class="blog-post-meta"><%= datebr(article.created_at) %> by <%= article.user.email %> in <strong class="d-inline-block mb-2 text-primary"><%= article.category.name %></strong></p>

app/views/articles/_elsewhere.html.erb
<div class="p-4">
  <h4 class="fst-italic">Elsewhere</h4>
    <ol class="list-unstyled">
      <li><a href="https://github.com/raposojoaopaulo" target="_blank">GitHub</a></li>
      <li><a href="https://github.com/raposojoaopaulo" target="_blank">Behance</a></li>
      <li><a href="https://www.linkedin.com/in/raposojoaopaulo/" target="_blank">Linkedin</a></li>
    </ol>
</div>

app/views/articles/_form.html.erb
<%= simple_form_for article do |form| %>
  
  <%= form.input :title %>
  <%= form.input :body, input_html: {rows: 10} %>
  <%= form.association :category, collection: Category.sorted, prompt: "Choose a Category..." %>

  <br>

  <p>  
  <%= form.button :submit, class: "btn btn-success" %>
  </p>
  
<% end %>

app/views/articles/_longer_featured.html.erb
<div class="p-4 p-md-5 mb-4 text-white rounded bg-dark">
  <div class="col-md-6 px-0">
    <h1 class="display-4 fst-italic"><%= article.title %></h1>
    <p class="lead my-3"><%= truncate(article.body, length: 140) %></p>
    <p class="lead mb-0">
      <%= link_to "Continue reading ...", article, class: "text-white fw-bold" %>
    </p>
  </div>
</div>

app/views/articles/_medium_featured.html.erb
<div class="col-md-6">
  <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
    <div class="col p-4 d-flex flex-column position-static">
      <strong class="d-inline-block mb-2 text-primary"><%= article.category.name %></strong>
      <h3 class="mb-0"><%= article.title %></h3>
      <div class="mb-1 text-muted"><%= datebr(article.created_at) %> by <%= article.user.email %></div>
        <p class="card-text mb-auto">
          <%= truncate(article.body, length: 100) %>
        </p>
        <%= link_to "Continue reading ...", article, class: "stretched-link" %>
    </div>
      <div class="col-auto d-none d-lg-block">
          <svg class="bd-placeholder-img" width="200" height="250" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>

      </div>
  </div>
</div>

app/views/articles/_pagination.html.erb
<nav class="blog-pagination" aria-label="Pagination">

  <%= link_to_next_page @articles, 'Older', class: "btn btn-outline-primary" %>
  <%= link_to_previous_page @articles, 'Newer', class: "btn btn-outline-primary" %>

</nav>

app/views/articles/_right_side.html.erb
<div class="col-md-4">
  <div class="position-sticky" style="top: 2rem;">
    <%= render "about" %>
    <%= render "archives" %>
    <%= render 'elsewhere' %>
  </div>
</div>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

  <%= render 'form', article: @article %>

<p>
  <%= link_to "Back", article_path(@article), class: "btn btn-secondary" %>
</p>

app/views/articles/index.html.erb
<h1>Articles</h1>
<%= render_if @highlights[0].present?, 'longer_featured', article: @highlights[0] %>

<div class="row mb-2">
  <%= render_if @highlights[1].present?, 'medium_featured', article: @highlights[1] %>
  <%= render_if @highlights[2].present?, 'medium_featured', article: @highlights[2] %>
</div>

<div class="row g-5">
  <div class="col-md-8">
      <h3 class="pb-4 mb-4 fst-italic border-bottom">
        For my learning
      </h3>

      <p><%= link_to "New Article", new_article_path, class: "btn btn-primary" if user_signed_in? %></p>

      <%= render @articles %>

      <%= render "pagination" %>

  </div>
  <%= render "right_side" %>
</div>

<%= content_for :category_filters do %>

 <div class="nav-scroller py-1 mb-2">
    <nav class="nav d-flex justify-content-between">
      <% @categories.each do |category| %>
        <%= link_to category.name, root_path(category: category.name), class: "p-2 link-secondary #{'category-active' if category.name.to_s == params[:category]}" %>
      <% end %>
  </div>

<% end %>

app/views/articles/new.html.erb
<h1>New Article</h1>

  <%= render 'form', article: @article %>

<p><%= link_to "Back", articles_path, class: "btn btn-secondary" %></p>

app/views/articles/show.html.erb
<article class="blog-post">
  <h2 class="blog-post-title"><%= @article.title %></h2>
  <p class="blog-post-meta"><%= render 'article_detail', article: @article %> </p>

  <p><%= @article.body %></p>

<p>
 <%= link_to "Back", articles_path, class: "btn btn-secondary" %>
 <%= link_to 'Edit', edit_article_path(@article), class: "btn btn-secondary" if policy(@article).update? %>
 <%= button_to 'Delete',  article_path(@article), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" if policy(@article).destroy? %></p>

</article>

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong>Name:</strong>
    <%= category.name %>
  </p>

</div>

app/views/categories/_form.html.erb
<%= simple_form_for(@category) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>
<p>
  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-success" %>
  </div>
</p>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<p style="color: green">

<h1>Categories</h1>

<p><%= link_to "New category", new_category_path, class: "btn btn-primary" %><p>

<table class="table table-striped table-hover table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Action</th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>  
        <td><%= category.name %></td>
        <td>
          <%= link_to "Show this category", category, class: "btn btn-link" %>
        <td>
      </tr>
    <% end %>
  <tbody>
</table>

<p><%= link_to "Back", articles_path, class: "btn btn-secondary" %></p>

<br>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Back", categories_path, class: "btn btn-secondary" %>
</div>

app/views/categories/show.html.erb
<p style="color: green">

<%= render @category %>

<div>
  <%= link_to "Edit this category", edit_category_path(@category), class: "btn btn-secondary" %>
  <%= link_to "Back to categories", categories_path, class: "btn btn-secondary" %>
  <p>
    <%= button_to "Destroy this category", @category, method: :delete, class: "btn btn-danger" %>
  </p>
</div>

app/views/layouts/_account_links.html.erb
<% if user_signed_in? %>

<div class="btn-group">
  <button class="btn btn-secondary btn-sm dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
    <%= current_user.email %>
  </button>&nbsp;
  <div class="btn-group" role="group" aria-label="Basic outlined example">  
    <%= link_to 'Edit User', edit_user_registration_path, class: "btn btn-sm btn-outline-secondary" %>&nbsp;
    <%= button_to 'Logout', destroy_user_session_path, method: :delete, class: "btn btn-sm btn-outline-danger" %>&nbsp;
  </div>
    
<% else %>
  <%= link_to 'Login', user_session_path, class: "btn btn-sm btn-outline-secondary" %>&nbsp;
  <%= link_to 'Register', new_user_registration_path, class: "btn btn-sm btn-outline-secondary" %>
<% end %>



app/views/layouts/_backup.html.erb
<% if user_signed_in? %>

<div class="dropdown">
  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
    <%= current_user.email %>
  </button>
  <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
    <li>
      <%= link_to 'Edit User', edit_user_registration_path, class: "dropdown-item" %>
    </li>
    <li><hr class="dropdown-divider"></li>
    <li>
     <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "dropdown-item" %>
    </li>
  </ul>
</div>
<% else %>
  <%= link_to 'Login', new_user_registration_path, class: "btn btn-sm btn-outline-secondary" %>
  <%= link_to 'Register', new_user_registration_path, class: "btn btn-sm btn-outline-secondary" %>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% if notice.present? %>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

<% if alert.present? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <%= alert %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>


app/views/layouts/_footer.html.erb
<footer class="blog-footer">
  <p>Blog template built for <a href="https://getbootstrap.com/">Bootstrap</a> by <a href="https://twitter.com/mdo">@mdo</a>.</p>
   <p>
    <a href="#">Back to top</a>
   </p>
</footer>

app/views/layouts/_topnavbar.html.erb
<div class="container">
  <header class="blog-header py-3">
    <div class="row flex-nowrap justify-content-between align-items-center">
      <div class="col-4 pt-1">
        <%= link_to "Categories", categories_path, class: 'link-secondary' %> 
      </div>

      <div class="col-4 text-center">
        <%= link_to "Blogstrap Teste", root_path, class: "blog-header-logo text-dark" %>
      </div>
      
      <div class="col-4 d-flex justify-content-end align-items-center">
        <%= render "layouts/account_links" %>
      </div>
    </div>
  </header>

 <%= yield :category_filters %>
</div>


app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogstrap2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://fonts.googleapis.com/css?family=Playfair&#43;Display:700,900&amp;display=swap" rel="stylesheet">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/topnavbar" %>
      <main class="container">
        <%= render "layouts/flash_messages" %>
        <%= yield %>
      </main>
    <%= render "layouts/footer" %>
  </body>
</html>